modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"

[[mods]]
modId="buildersbackpacks"
version="0.0.1"
displayName="Builder's Backpacks"
authors="Mithion" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A simple mod that makes setting up resources easier for builders in creative and survival alike!
'''

[[dependencies.buildersbackpacks]]    
    modId="forge" #mandatory
    mandatory=true
    versionRange="[34,)"    
    ordering="NONE"
    side="BOTH"
[[dependencies.buildersbackpacks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
